services:
 hugo:
    image: "ghcr.io/gohugoio/hugo:v0.151.2"
    environment: 
    - "HUGO_ENV=production"
    # Permet d'utiliser l'utilisateur root
    user: "0:0"
    # Obligatoire de préciser le chemin de travail avec l'image officielle
    working_dir: /src
    # La commande ci-dessous est obligatoire achever le point d'entrée hugo et lancer le shell pour exécuter les commandes nécessaires.
    entrypoint: [""]
    command: sh -c "
      hugo && \
      apk add nodejs npm && \
      npm install -g pagefind@1.3.0 && \
      pagefind --site ./public/postes/ && \
      hugo server --appendPort=false --baseURL="floraud.fr/" --bind=0.0.0.0"
    volumes:
      - "/volume2/docker/floraud-website-gohugo/src:/src"
      - "/volume2/docker/floraud-website-gohugo/hugo_cache:/tmp/hugo_cache"
    ports:
      - "1313:1313"