services:
  hugo:
    image: "hugomods/hugo:base-0.140.2"
    # La commande ci-dessous est obligatoire pour lancer le service
    command: sh -c "
      hugo --minify && \
      apk add --no-cache nodejs npm && \
      npm install -g pagefind && \
      pagefind --site ./public/postes/ && \
      server"

    volumes:
      - "$PWD/src:/src"
      - "$PWD/hugo_cache:/tmp/hugo_cache"
    ports:
      - "1313:1313"