services:
  hugo:
    image: "hugomods/hugo:base-0.140.2" # image officielle ne fonctionne pas pour l'install de pagefind
    environment: 
    - "HUGO_ENV=production"
    # La commande ci-dessous est obligatoire pour lancer le service
    command: sh -c "
      hugo && \
      apk add nodejs npm && \
      npm install -g pagefind && \
      pagefind --site ./public/postes/ && \
      server --appendPort=false --baseURL="floraud.fr/""
    volumes:
      - "$PWD/src:/src"
      - "$PWD/hugo_cache:/tmp/hugo_cache"
    ports:
      - "1313:1313"