services:
  hugo:
    image: "hugomods/hugo:base-0.140.2"
    environment: 
    - "HUGO_ENV=production"
    # La commande ci-dessous est obligatoire pour lancer le service
    command: server --appendPort=false --baseURL="floraud.fr/"
    volumes:
      - "/volume1/docker/floraud-website-gohugo/src:/src"
      - "/volume1/docker/floraud-website-gohugo/hugo_cache:/tmp/hugo_cache"
    ports:
      - "1313:1313"