services:
  hugo:
    image: "hugomods/hugo:base-0.148.1" # image officielle ne fonctionne pas pour l'install de pagefind
    environment: 
    - "HUGO_ENV=production"
    # La commande ci-dessous dans cet ordre est obligatoire pour lancer le service car il faut d'abord build le site pour que pagefind puisse l'indexer avant de le lancer.
    command: sh -c "
      hugo && \
      apk add nodejs npm && \
      npm install -g pagefind@1.3.0 && \
      pagefind --site ./public/postes/ && \
      server --appendPort=false --baseURL="floraud.fr/""
    volumes:
      - "/volume2/docker/floraud-website-gohugo/src:/src"
      - "/volume2/docker/floraud-website-gohugo/hugo_cache:/tmp/hugo_cache"
    ports:
      - "1313:1313"