title = "Floraud"
baseURL = "https://floraud.fr"
languageCode = "fr"
theme = ["gohugo-theme-ananke"]
# Dossier dans lequel seront stockés des fichiers optimisés que Hugo traite en interne
resourceDir = "../resources"
# La description ci-dessous aide à la description des metadata
description = "Blog personnel sur la tech et mes autres passions"

DefaultContentLanguage = "fr"
# Commenter la section du dessous permet de ne pas reprendre automatiquement les dossiers comme "content/postes/"
# SectionPagesMenu = "main"

# Nombre d'article par page
pagination.pagerSize = 9
enableRobotsTXT = true

[sitemap]
  # Permet au moteur de recherche d'indexer plus efficacement le site en suivant les consignes
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Floraud"
  favicon = ""
  site_logo = ""
  # La description ci-dessous permet de reprendre ce paramètre dans un template
  description = "Le blog d'un passionné d'informatique à propos de ses loisirs"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[params.ananke.social]
  [params.ananke.social.follow]
  new_window_icon = true
  networks = [
  "gitlab",
  "github"
  ]

[params.ananke.social.gitlab]
username = "Floraud"

[params.ananke.social.github]
username = "Floraud"

[params.ananke.social.share]
icons = true
sharetext = true
networks = [
  "email",
  "linkedin",
  "mastodon",
  "facebook",
]

[[menu.main]]
   name = "Tech"
   url = "/categories/tech/"
   weight = 10

[[menu.main]]
  name = "Maison"
  url = "/categories/maison/"
  weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"

# Nécessaire pour accepter l'ajout d'html dans une page comme la recherche actuelle dans _index.md  (voir si on peut faire autrement)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true